# Generated by Django 2.2 on 2023-06-20 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0002_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='hobbies',
            name='hobby_image',
            field=models.CharField(default='https://img.freepik.com/free-photo/high-angle-person-doing-bead-work_23-2148815811.jpg', max_length=500),
        ),
    ]
