# Generated by Django 2.2 on 2023-06-20 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PortfolioDatabase', '0004_auto_20230619_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_image',
            field=models.CharField(default='https://creazilla-store.fra1.digitaloceanspaces.com/cliparts/3162705/portfolio-clipart-md.png', max_length=500),
        ),
    ]
